# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:
- group: New variable group 05-7月
- name: app-location
  value: '123'

pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
- script: npm installer
- script: npm test
- script: |
    echo Starting the build
    mvn package
  displayName: 'Build with Maven'
  env:
    MY_MAPPED_ENV_VAR: $(system.teamProject)
- powershell: |
    # Using an input-macro:
    Write-Host "This works: $(system.teamProject)"  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

